version: '3.8'

networks:
  public:
    driver: bridge

volumes:
  mysql:
    driver: local

x-common-variables: &common-variables
  MYSQL_DATABASE: quizdb
  MYSQL_USER: quiz
  MYSQL_PASSWORD: quiz

services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 3001:3001
    networks:
      - public
   

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_NATIVE_PACKAGER_HOSTNAME=127.0.0.1
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=127.0.0.1
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    networks:
      - public      

  db:
    image: mysql:5.7
    container_name: db
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: quizdb
      MYSQL_USER: quiz
      MYSQL_PASSWORD: quiz
    ports:
      - "3306:3306"
    volumes:
      - ~/.quizapp/data/mysql:/var/lib/mysql 
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    networks:
      - public


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - public
